### ISSUE TITLE
Nonsense 

### ISSUE THREAD

**Issue by Gre4ko** [Drayff/Binogic#1]
why in the code "matrix[0].length" 
```java 
JPanel panel = new JPanel(new GridLayout(matrix.length, matrix[0].length)); 
```
if we create square matrices in which the columns and rows are the same in number?
```java
public static int[][] createMatrix(int sizeOfMatrix) {
        int[][] matrix = new int[sizeOfMatrix][sizeOfMatrix];
```

**Comment by Drayff** [comment]
Thank you for your comment. Indeed, this code is redundant, I’ll fix it now.
